### PR TITLE
more updates

### PR DESCRIPTION
**Pull request by eyecubed**
furnator, reactor desc and casing

### CODE REVIEW

**Comment by Gcat101** [comment]
You know you can commit without redoing the pull request lmao

**Comment by Gcat101** [comment]
:trollface:

**Comment by eyecubed** [comment]
yeah i completed it
How cool right
is this how github works im becoming a boomer

**Comment by Gcat101** [comment]
My man

**Comment by Gcat101** [comment]
I’m just gonna assume that this works because we have changed how lang keys work a bit and idr if I made it so that the old format still works

**Comment by Gcat101** [comment]
Nvm I checked and I did, lgtm

**Pull request merged**
